### PR TITLE
Updating system to use new prop-types package.

### PR DESCRIPTION
**Pull request by Meandmybadself**
Updated prop-types usage globally to conform to newer standards.

Thanks for this library!

### CODE REVIEW

**Comment by iongion** [comment]
+1 to merge this

**Comment by scragg0x** [comment]
@seal789ie Please merge and publish this asap!

**Comment by esaulnier** [comment]
:+1:

**Comment by Mike-Bell** [comment]
pls respond

**Comment by EmanuelaGr** [comment]
@seal789ie Please merge and publish this asap!

**Comment by rachelnicole** [comment]
+1 Please merge.

**Pull request merged**
